spring:
  datasource:
#    Specify DBMS driver, url:port and database name
    url: jdbc:postgresql://localhost:5432/departmentmanagement
    username: manager
    password: bestmanager1989
#  Database migration help us not to rely on SQL generation and allow us to update database consistently
  flyway:
    locations: classpath:migration
  jpa:
    open-in-view: false